"""Public application use cases and contracts."""

from dj_digger.core.application.analyze import AnalyzeRequest, AnalyzeUseCase
from dj_digger.core.application.app import CoreApplication
from dj_digger.core.application.copy_set import CopySetRequest, CopySetUseCase, SetCopyResult
from dj_digger.core.application.curation import (
    CurationAuthenticationError,
    CurationClientError,
    CurationGroundingError,
    CurationMCPError,
    CurationRequest,
    CurationResponseError,
    CurationResult,
    CurationTimeoutError,
    CurationTransportError,
    CurationTurnLimitError,
    CurationUseCase,
)
from dj_digger.core.application.duplicates import (
    DuplicateAnalysisResult,
    DuplicateAnalyzeRequest,
    DuplicateAnalyzeUseCase,
    DuplicateGroupDescription,
    DuplicateListRequest,
    DuplicateListUseCase,
    DuplicateMarkBestRequest,
    DuplicateMarkBestUseCase,
    QualityMarkResult,
)
from dj_digger.core.application.export import (
    ExportMaintenanceWarning,
    ExportRequest,
    ExportResult,
    ExportUseCase,
)
from dj_digger.core.application.jobs import (
    JobRecord,
    JobRepository,
    JobStateError,
    JobStatus,
    JobsUseCase,
)
from dj_digger.core.application.metadata import MetadataRequest, MetadataRunResult, MetadataUseCase
from dj_digger.core.application.operations import (
    DatabaseIntegrityCheckResult,
    DatabaseOptimizeResult,
    DatabaseQuickCheckResult,
    DatabaseRebuildResult,
    DoctorResult,
    DoctorUseCase,
    IntegrityCheckDatabaseUseCase,
    OptimizeDatabaseUseCase,
    QuickCheckDatabaseUseCase,
    RebuildCurrentAnalysisUseCase,
    StatusResult,
    StatusUseCase,
)
from dj_digger.core.application.refresh import (
    RefreshRequest,
    RefreshResult,
    RefreshUseCase,
    worst_status,
)
from dj_digger.core.application.scan import (
    ScanRequest,
    ScanRunResult,
    ScanSourceResult,
)
from dj_digger.core.application.snapshot import SnapshotRequest, SnapshotResult, SnapshotUseCase
from dj_digger.core.errors import (
    CoreError,
    DependencyError,
    DependencyTimeoutError,
    IntegrityError,
    InvalidInputError,
    ResourceNotFoundError,
    StateConflictError,
)
from dj_digger.core.progress import (
    AnalysisProgressReporter,
    NullProgressReporter,
    ProgressEvent,
    ProgressEventReporter,
    ProgressReporter,
    ProgressSink,
)

__all__ = [
    "CoreApplication",
    "CurationAuthenticationError",
    "CurationClientError",
    "CurationGroundingError",
    "CurationMCPError",
    "CurationRequest",
    "CurationResponseError",
    "CurationResult",
    "CurationTimeoutError",
    "CurationTransportError",
    "CurationTurnLimitError",
    "CurationUseCase",
    "CopySetRequest",
    "CopySetUseCase",
    "SetCopyResult",
    "ExportRequest",
    "ExportResult",
    "ExportUseCase",
    "ExportMaintenanceWarning",
    "AnalyzeRequest",
    "AnalyzeUseCase",
    "DatabaseIntegrityCheckResult",
    "DatabaseOptimizeResult",
    "DatabaseQuickCheckResult",
    "DatabaseRebuildResult",
    "DuplicateAnalysisResult",
    "DuplicateAnalyzeRequest",
    "DuplicateAnalyzeUseCase",
    "DuplicateGroupDescription",
    "DuplicateListRequest",
    "DuplicateListUseCase",
    "DuplicateMarkBestRequest",
    "DuplicateMarkBestUseCase",
    "DoctorResult",
    "DoctorUseCase",
    "AnalysisProgressReporter",
    "CoreError",
    "DependencyError",
    "DependencyTimeoutError",
    "IntegrityError",
    "InvalidInputError",
    "IntegrityCheckDatabaseUseCase",
    "JobRecord",
    "JobRepository",
    "JobStateError",
    "JobStatus",
    "JobsUseCase",
    "MetadataRequest",
    "MetadataRunResult",
    "MetadataUseCase",
    "ProgressEvent",
    "ProgressEventReporter",
    "ProgressReporter",
    "ProgressSink",
    "RefreshRequest",
    "RefreshResult",
    "RefreshUseCase",
    "QualityMarkResult",
    "NullProgressReporter",
    "OptimizeDatabaseUseCase",
    "QuickCheckDatabaseUseCase",
    "RebuildCurrentAnalysisUseCase",
    "ResourceNotFoundError",
    "ScanRequest",
    "ScanRunResult",
    "ScanSourceResult",
    "StateConflictError",
    "StatusResult",
    "StatusUseCase",
    "SnapshotRequest",
    "SnapshotResult",
    "SnapshotUseCase",
    "worst_status",
]
